name: Node.js CI

on:
   push:
     branches: [ "main" ]
   pull_requiest: [ "main" ]

jobs:
   test:
     runs-on: ubuntu-latest

     setps:
     - uses: actions/chekout@v3
     
     - name: Use Node.js
       uses: actions/setup-node@v3
       with:
         node-version: 18

     - name: Install dependencies
       run: npm install

     - name: Fix jest permissions
       run: chmod +x ./node_modules/.bin/jest

     - name: run tests
       run: npm test